export const GET_RECIPES = 'GET_RECIPES';
export const LOADING_RECIPES = 'LOADING_RECIPES';
export const GET_FACEBOOK = 'GET_FACEBOOK';
export const LOGOUT_FACEBOOK = 'LOGOUT_FACEBOOK';
export const GET_FACEBOOK_ERROR = 'GET_FACEBOOK_ERROR';
