# Generated by Django 3.0.8 on 2020-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
